---
- hosts: all

  vars:
    sites_dir: /home/vagrant/sites

  vars_files:
    - ../settings.yml

  tasks:

    - name: Nginx | add vhost
      template: src=templates/server_block.j2 dest=/etc/nginx/sites-available/{{ item['alias'] }}
      tags: nginx
      sudo: true
      with_items:
        - "{{ vhosts }}"

    - name: Nginx | enable vhosts
      file: src=/etc/nginx/sites-available/{{ item['alias'] }} dest=/etc/nginx/sites-enabled/{{ item['alias'] }} state=link
      tags: nginx
      sudo: true
      with_items:
        - "{{ vhosts }}"
      notify:
        - restart nginx
        - restart fpm

    - name: MySQL | create applications databases
      mysql_db: name={{ item["db"] }} state=present login_password={{ mysql_root_password }} login_user=root collation={{ mysql_collation_server }}
      tags: mysql
      with_items:
        - "{{ vhosts }}"

  handlers:
      - include: common/handlers/main.yml
